### ISSUE TITLE
pnpm v6 support

### ISSUE THREAD

**Issue by travi** [zkochan/package-preview#73]
now that v6 of `pnpm` is released as latest, i've found that my projects that use `package-preview` have been breaking upon installation of `pnpm` with errors like the following: https://github.com/travi/javascript-scaffolder/runs/2304674064?check_suite_focus=true#step:5:535

i found that the behavior of installing the latest `pnpm` is due to the dependency on `@pnpm/self-installer` and was able to use the `PNPM_VERSION` environment variaable mentioned in [Configuring](https://github.com/pnpm/self-installer#configuring) to pin pnpm to `latest-5`.

it would be great if `package-preview` were compatible with the version of `pnpm` installed by default. i also see that `@pnpm/self-installer` is deprecated and the repo is archived, so this update would likely require adjustment to use the modern approach.

**Comment by zkochan** [comment]
fixed in v4

**Comment by travi** [comment]
thanks a lot for the super fast resolution. really appreciate it!
